name: swaaba_aralee
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  http: ^1.2.2 # Updated to latest stable
  dio: ^5.7.0 # Updated to latest stable
  flutter_secure_storage: ^9.2.2 # Updated to latest stable
  shared_preferences: ^2.3.2 # Updated to latest stable
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0
  flutter_carousel_widget: ^2.2.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/car_image.jpg
    - lib/assets/hot_cars/lan.png
    - lib/assets/hot_cars/alphard.png
    - lib/assets/hot_cars/prad.png
    - lib/assets/E_cars/premium.png
    - lib/assets/E_cars/hybrid.png
    - lib/assets/E_cars/luxury.png
    - lib/assets/E_cars/popular.png
    - lib/assets/toyota.png
    - lib/assets/screen11.jpg
    - lib/assets/screen2.avif
    - lib/assets/screen3.avif
    - lib/assets/Nissan.png
    - lib/assets/Subaru.png
    - lib/assets/Mercedenz.png
    - lib/assets/mitshubi.png
    - lib/assets/landRover.png
    - lib/assets/premium/car1.jpeg
    - lib/assets/premium/car2.jpg
    - lib/assets/premium/car3.jpg
    - lib/assets/premium/car4.jpg
    - lib/assets/premium/car5.jpg
    - lib/assets/premium/car6.jpg
    - lib/assets/luxury/car1.jpg
    - lib/assets/luxury/car2.jpg
    - lib/assets/luxury/car3.jpg
    - lib/assets/luxury/car4.jpg
    - lib/assets/luxury/car5.jpg
    - lib/assets/luxury/car6.jpg
    - lib/assets/hybrid/car1.jpg
    - lib/assets/hybrid/car2.jpg
    - lib/assets/hybrid/car3.jpg
    - lib/assets/hybrid/car4.jpg
    - lib/assets/hybrid/car5.jpg
    - lib/assets/hybrid/car6.jpg
    - lib/assets/avatar.jpg
    - lib/assets/onboarding/home.png
    - lib/assets/onboarding/find.png
    - lib/assets/onboarding/login.png
    - lib/assets/hybrid/hybrid1_back.jpg
    - lib/assets/hybrid/hybrid1_front.jpg
    - lib/assets/hybrid/hybrid1_inside.jpg
    - lib/assets/hybrid/hybrid1_beside.jpg
    - lib/assets/hybrid/hybrid2_front.jpg
    - lib/assets/hybrid/hybrid2_back.jpg
    - lib/assets/hybrid/hybrid2_inside.jpg
    - lib/assets/hybrid/hybrid2_beside.jpg
