name: swaaba_aralee
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.1
  share_plus: ^9.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets 
  assets:
      - lib/assets/logo.png
      - lib/assets/car_image.jpg
      - lib/assets/hot_cars/lan.png
      - lib/assets/hot_cars/alphard.png
      - lib/assets/hot_cars/prad.png
      - lib/assets/E_cars/premium.png
      - lib/assets/E_cars/hybrid.png
      - lib/assets/E_cars/luxury.png
      - lib/assets/E_cars/popular.png
      - lib/assets/toyota.png
      - lib/assets/Nissan.png
      - lib/assets/Subaru.png
      - lib/assets/Mercedenz.png
      - lib/assets/mitshubi.png
      - lib/assets/landRover.png
